// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Mazhar Ahmed

//! Quran resolver.
//!
//! Reads `quran/chapters/{surah}.json` — one file per Surah, so `Q:2:255`
//! loads roughly 50 KB rather than the whole mushaf.
//!
//! That directory is generated by `scripts/build-quran.py` and committed: the
//! Arabic comes from Tanzil's Uthmani text, which uses standard Unicode marks,
//! while `quran-json-arabic` spells three of them with codepoints that mean
//! something else (U+0657 for an open fathatan, and so on) — enough to make
//! 2:286 read *isru* instead of *isran* in any font that follows Unicode.
//! Names, translation and transliteration still come from that project, which
//! is fetched on demand when rebuilding rather than carried as a submodule.

use crate::ast::Reference;
use crate::error::Error;
use crate::record::Record;
use crate::repo::Repository;
use crate::sources::Source;
use serde::Deserialize;

const SURAH_COUNT: u32 = 114;
const DIR: &str = "quran/chapters";

/// Ayah count of each Surah, in order.
///
/// Islamic-book structure, which is exactly what a source handler is allowed
/// to know. It lets `Q::N` locate the N-th ayah of the mushaf arithmetically
/// and read the one chapter file it lives in, instead of shipping a second
/// copy of the whole text as 6236 per-ayah files. A test checks every entry
/// against the data.
const SURAH_VERSES: [u32; SURAH_COUNT as usize] = [
    7, 286, 200, 176, 120, 165, 206, 75, 129, 109, 123, 111,
    43, 52, 99, 128, 111, 110, 98, 135, 112, 78, 118, 64,
    77, 227, 93, 88, 69, 60, 34, 30, 73, 54, 45, 83,
    182, 88, 75, 85, 54, 53, 89, 59, 37, 35, 38, 29,
    18, 45, 60, 49, 62, 55, 78, 96, 29, 22, 24, 13,
    14, 11, 11, 18, 12, 12, 30, 52, 52, 44, 28, 28,
    20, 56, 40, 31, 50, 40, 46, 42, 29, 19, 36, 25,
    22, 17, 19, 26, 30, 20, 15, 21, 11, 8, 8, 19,
    5, 8, 8, 11, 11, 8, 3, 9, 5, 4, 7, 3,
    6, 3, 5, 4, 5, 6,
];

/// Ayat in the whole mushaf. Derived, so it cannot drift from the table.
const AYAH_COUNT: u32 = total_ayat();

const fn total_ayat() -> u32 {
    let mut total = 0;
    let mut index = 0;
    while index < SURAH_VERSES.len() {
        total += SURAH_VERSES[index];
        index += 1;
    }
    total
}

/// Split a mushaf-wide ayah number into `(surah, ayah)`.
fn locate(global: u32) -> Option<(u32, u32)> {
    if global == 0 {
        return None;
    }
    let mut remaining = global;
    for (index, &count) in SURAH_VERSES.iter().enumerate() {
        if remaining <= count {
            let surah = u32::try_from(index).ok()?.checked_add(1)?;
            return Some((surah, remaining));
        }
        remaining -= count;
    }
    None
}

/// `Q` — the Quran.
#[derive(Debug, Default)]
pub struct Quran;

#[derive(Debug, Deserialize)]
struct Chapter {
    name: String,
    transliteration: String,
    verses: Vec<Verse>,
}

#[derive(Debug, Deserialize)]
struct Verse {
    id: u32,
    text: String,
    translation: String,
}

impl Source for Quran {
    fn code(&self) -> &str {
        "Q"
    }

    fn name(&self) -> &str {
        "Quran"
    }

    fn total(&self, _repo: &mut Repository) -> Result<Option<u32>, Error> {
        Ok(Some(AYAH_COUNT))
    }

    fn resolve(
        &self,
        repo: &mut Repository,
        reference: &Reference,
        out: &mut Vec<Record>,
    ) -> Result<(), Error> {
        // `Q::100` — count ayat across the whole mushaf instead of within a
        // Surah.
        let Some(surah) = reference.primary else {
            return self.resolve_flat(repo, reference, out);
        };

        // The parser cheerfully accepts Q:0 and Q:115; rejecting them is this
        // module's job, not its.
        if surah == 0 || surah > SURAH_COUNT {
            return Err(Error::ReferenceNotFound {
                detail: format!("Surah {surah} (Quran has 1..=114)"),
            });
        }

        let chapter: std::sync::Arc<Chapter> = repo.load(format!("{DIR}/{surah}.json"))?;

        let total = u32::try_from(chapter.verses.len()).map_err(|_| Error::InvalidDataFile {
            path: format!("{DIR}/{surah}.json"),
            detail: "implausible verse count".into(),
        })?;

        for ayah in reference.expand(total)? {
            // Files are ordered and complete, but index by `id` rather than
            // trusting position.
            let verse = chapter
                .verses
                .iter()
                .find(|v| v.id == ayah)
                .ok_or_else(|| Error::ReferenceNotFound {
                    detail: format!("Q:{surah}:{ayah}"),
                })?;

            out.push(Record {
                source: self.code().to_string(),
                collection: self.name().to_string(),
                extra: [
                    ("surah".to_string(), surah.into()),
                    ("surah_name_ar".to_string(), chapter.name.clone().into()),
                    (
                        "surah_name_en".to_string(),
                        chapter.transliteration.clone().into(),
                    ),
                    ("ayah".to_string(), ayah.into()),
                ]
                .into_iter()
                .collect(),
                ar: verse.text.clone(),
                en: verse.translation.clone(),
            });
        }

        Ok(())
    }
}

impl Quran {
    /// `Q::N` — the N-th ayah of the mushaf, 1..=6236.
    ///
    /// Resolved through [`locate`] and the ordinary chapter files, so the
    /// Arabic here is the same bytes `Q:2:93` returns — there is only ever one
    /// copy of the text on disk.
    fn resolve_flat(
        &self,
        repo: &mut Repository,
        reference: &Reference,
        out: &mut Vec<Record>,
    ) -> Result<(), Error> {
        for number in reference.expand(AYAH_COUNT)? {
            let (surah, ayah) = locate(number).ok_or_else(|| Error::ReferenceNotFound {
                detail: format!("Q::{number}"),
            })?;

            let path = format!("{DIR}/{surah}.json");
            let chapter: std::sync::Arc<Chapter> = repo.load(&path)?;

            let verse = chapter
                .verses
                .iter()
                .find(|v| v.id == ayah)
                .ok_or_else(|| Error::ReferenceNotFound {
                    detail: format!("Q::{number} (Q:{surah}:{ayah})"),
                })?;

            out.push(Record {
                source: self.code().to_string(),
                collection: self.name().to_string(),
                extra: [
                    ("surah".to_string(), surah.into()),
                    ("surah_name_ar".to_string(), chapter.name.clone().into()),
                    (
                        "surah_name_en".to_string(),
                        chapter.transliteration.clone().into(),
                    ),
                    ("ayah".to_string(), ayah.into()),
                    ("number".to_string(), number.into()),
                    ("numbering".to_string(), "book".into()),
                ]
                .into_iter()
                .collect(),
                ar: verse.text.clone(),
                en: verse.translation.clone(),
            });
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_table_covers_the_whole_mushaf() {
        assert_eq!(SURAH_VERSES.len(), 114);
        assert_eq!(AYAH_COUNT, 6236);
    }

    #[test]
    fn locate_maps_the_edges_of_the_mushaf() {
        assert_eq!(locate(1), Some((1, 1)));
        assert_eq!(locate(7), Some((1, 7)));
        assert_eq!(locate(8), Some((2, 1)));
        assert_eq!(locate(100), Some((2, 93)));
        assert_eq!(locate(AYAH_COUNT), Some((114, 6)));
        assert_eq!(locate(AYAH_COUNT + 1), None);
        // Expansion rejects 0 before this is reached, but do not invent an
        // ayah 0 for anyone who calls it directly.
        assert_eq!(locate(0), None);
    }
}
