// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Mazhar Ahmed

//! Quran resolver.
//!
//! Reads `quran/chapters/{surah}.json` — one file per Surah, so `Q:2:255`
//! loads roughly 50 KB rather than the whole mushaf.
//!
//! That directory is generated by `scripts/build-quran.py`, not vendored: the
//! Arabic comes from Tanzil's Uthmani text, which uses standard Unicode marks,
//! while the `quran-json-arabic` submodule spells three of them with
//! codepoints that mean something else (U+0657 for an open fathatan, and so
//! on) — enough to make 2:286 read *isru* instead of *isran* in any font that
//! follows Unicode. Names, translation and transliteration still come from the
//! submodule.

use crate::ast::Reference;
use crate::error::Error;
use crate::record::Record;
use crate::repo::Repository;
use crate::sources::Source;
use serde::Deserialize;

const SURAH_COUNT: u32 = 114;
const AYAH_COUNT: u32 = 6236;
const DIR: &str = "quran/chapters";
const VERSE_DIR: &str = "quran/verses";

/// `Q` — the Quran.
#[derive(Debug, Default)]
pub struct Quran;

#[derive(Debug, Deserialize)]
struct Chapter {
    name: String,
    transliteration: String,
    verses: Vec<Verse>,
}

#[derive(Debug, Deserialize)]
struct Verse {
    id: u32,
    text: String,
    translation: String,
}

/// `quran/verses/{n}.json` — one file per ayah in mushaf order, carrying its
/// Surah alongside, which is what makes `Q::100` resolvable without an index.
#[derive(Debug, Deserialize)]
struct GlobalVerse {
    /// Ayah number within its Surah.
    number: u32,
    text: String,
    translations: std::collections::BTreeMap<String, String>,
    chapter: GlobalChapter,
}

#[derive(Debug, Deserialize)]
struct GlobalChapter {
    id: u32,
    name: String,
    transliteration: String,
}

impl Source for Quran {
    fn code(&self) -> &str {
        "Q"
    }

    fn name(&self) -> &str {
        "Quran"
    }

    fn resolve(
        &self,
        repo: &mut Repository,
        reference: &Reference,
        out: &mut Vec<Record>,
    ) -> Result<(), Error> {
        // `Q::100` — count ayat across the whole mushaf instead of within a
        // Surah.
        let Some(surah) = reference.primary else {
            return self.resolve_flat(repo, reference, out);
        };

        // The parser cheerfully accepts Q:0 and Q:115; rejecting them is this
        // module's job, not its.
        if surah == 0 || surah > SURAH_COUNT {
            return Err(Error::ReferenceNotFound {
                detail: format!("Surah {surah} (Quran has 1..=114)"),
            });
        }

        let chapter: std::sync::Arc<Chapter> = repo.load(format!("{DIR}/{surah}.json"))?;

        let total = u32::try_from(chapter.verses.len()).map_err(|_| Error::InvalidDataFile {
            path: format!("{DIR}/{surah}.json"),
            detail: "implausible verse count".into(),
        })?;

        for ayah in reference.expand(total)? {
            // Files are ordered and complete, but index by `id` rather than
            // trusting position.
            let verse = chapter
                .verses
                .iter()
                .find(|v| v.id == ayah)
                .ok_or_else(|| Error::ReferenceNotFound {
                    detail: format!("Q:{surah}:{ayah}"),
                })?;

            out.push(Record {
                source: self.code().to_string(),
                collection: self.name().to_string(),
                extra: [
                    ("surah".to_string(), surah.into()),
                    ("surah_name_ar".to_string(), chapter.name.clone().into()),
                    (
                        "surah_name_en".to_string(),
                        chapter.transliteration.clone().into(),
                    ),
                    ("ayah".to_string(), ayah.into()),
                ]
                .into_iter()
                .collect(),
                ar: verse.text.clone(),
                en: verse.translation.clone(),
            });
        }

        Ok(())
    }
}

impl Quran {
    /// `Q::N` — the N-th ayah of the mushaf, 1..=6236.
    fn resolve_flat(
        &self,
        repo: &mut Repository,
        reference: &Reference,
        out: &mut Vec<Record>,
    ) -> Result<(), Error> {
        for number in reference.expand(AYAH_COUNT)? {
            let verse: std::sync::Arc<GlobalVerse> =
                repo.load(format!("{VERSE_DIR}/{number}.json"))?;

            out.push(Record {
                source: self.code().to_string(),
                collection: self.name().to_string(),
                extra: [
                    ("surah".to_string(), verse.chapter.id.into()),
                    ("surah_name_ar".to_string(), verse.chapter.name.clone().into()),
                    (
                        "surah_name_en".to_string(),
                        verse.chapter.transliteration.clone().into(),
                    ),
                    ("ayah".to_string(), verse.number.into()),
                    ("number".to_string(), number.into()),
                    ("numbering".to_string(), "book".into()),
                ]
                .into_iter()
                .collect(),
                ar: verse.text.clone(),
                en: verse
                    .translations
                    .get("en")
                    .cloned()
                    .unwrap_or_default(),
            });
        }

        Ok(())
    }
}
